# Generated by Django 5.0.11 on 2025-04-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="channel_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
