# Generated by Django 5.0.11 on 2025-04-08 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0002_alter_channel_channel_date_alter_post_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="posts",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="thoughtswap.post",
            ),
        ),
    ]
