# Generated by Django 5.0.11 on 2025-04-08 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0003_alter_channel_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="posts",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="thoughtswap.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="responses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_responses",
                to="thoughtswap.response",
            ),
        ),
    ]
