# Generated by Django 5.0.11 on 2025-04-08 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0006_channel_channel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="thoughtswap.channel",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="participants",
            field=models.ManyToManyField(
                default="No Participantss", to="thoughtswap.participant"
            ),
        ),
    ]
