# Generated by Django 5.0.11 on 2025-04-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0007_remove_channel_posts_post_channel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="channel",
        ),
        migrations.AddField(
            model_name="channel",
            name="posts",
            field=models.ManyToManyField(
                related_name="channels", to="thoughtswap.post"
            ),
        ),
    ]
