# Generated by Django 5.0.11 on 2025-04-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0008_remove_post_channel_channel_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="posts",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="channels", to="thoughtswap.post"
            ),
        ),
    ]
