# Generated by Django 5.0.11 on 2025-04-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0009_alter_channel_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="prompt",
            field=models.TextField(default="No current prompt set"),
        ),
    ]
