# Generated by Django 5.0.11 on 2025-04-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0010_post_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="posts",
            field=models.ManyToManyField(
                blank=True, related_name="channels", to="thoughtswap.post"
            ),
        ),
    ]
