# Generated by Django 5.0.11 on 2025-04-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0011_alter_channel_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="response_date",
            field=models.DateField(),
        ),
    ]
