# Generated by Django 5.0.11 on 2025-04-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0012_alter_response_response_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="responses",
        ),
        migrations.AddField(
            model_name="post",
            name="responses",
            field=models.ManyToManyField(to="thoughtswap.response"),
        ),
    ]
