# Generated by Django 5.0.11 on 2025-04-08 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0014_alter_channel_creator_alter_post_facilitator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="posts",
        ),
        migrations.AddField(
            model_name="channel",
            name="post",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channels",
                to="thoughtswap.post",
            ),
        ),
    ]
