# Generated by Django 5.0.11 on 2025-04-09 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0015_remove_channel_posts_channel_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="channel_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="thoughtswap.channel",
            ),
        ),
    ]
