# Generated by Django 5.0.11 on 2025-04-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0016_post_channel_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="responses",
        ),
        migrations.AddField(
            model_name="response",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="thoughtswap.post",
            ),
        ),
    ]
