# Generated by Django 5.0.11 on 2025-04-09 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0017_remove_post_responses_response_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="channel_date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
