# Generated by Django 5.0.11 on 2025-05-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0019_alter_post_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="response_content",
            field=models.TextField(verbose_name="No current response set"),
        ),
    ]
