# Generated by Django 5.0.11 on 2025-05-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0020_alter_response_response_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="response_content",
            field=models.TextField(default="No current response set"),
        ),
    ]
