# Generated by Django 5.0.11 on 2025-05-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtswap', '0021_alter_response_response_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_code',
            field=models.CharField(default='code', max_length=10),
        ),
    ]
