# Generated by Django 5.0.11 on 2025-05-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtswap', '0022_channel_channel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_code',
            field=models.CharField(default='Code', max_length=255),
        ),
    ]
