# Generated by Django 5.0.11 on 2025-04-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("facilitator", "Facilitator"),
                    ("participant", "Participant"),
                ],
                default="no role",
                max_length=11,
            ),
        ),
    ]
