# Generated by Django 5.0.11 on 2025-04-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0017_remove_post_responses_response_post"),
        ("users", "0003_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_posts",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="saved_by", to="thoughtswap.post"
            ),
        ),
    ]
