# Generated by Django 5.0.11 on 2025-04-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0017_remove_post_responses_response_post"),
        ("users", "0004_user_saved_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="saved_posts",
            field=models.ManyToManyField(
                blank=True, related_name="saved_by", to="thoughtswap.post"
            ),
        ),
    ]
